{
 "title": "BT_EX-Dashboard",
 "time": { "from": "2022-12-15T10:10:39.000Z", "to": "2022-12-16T10:09:58.000Z" },
 "templating": {
  "list": [
   {
    "name": "label",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"label\",\r\n    predicate: (r) => true,\r\n    start: 0\r\n)"
   },
   { "name": "period", "label": "Period of aggregation", "query": "1s" },
   { "name": "l4", "label": "Layer 4", "query": "UDP" },
   { "name": "port", "label": "Port", "query": "443" }
  ]
 },
 "panels": [
  {
   "title": "Click the button below to search and set the full timeline of $label (blue means full timeline is shown)",
   "type": "williamvenner-timepickerbuttons-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"join\"\r\n\r\nall = from(bucket: \"BT_EX\")\r\n      |> range(start: 0)\r\n      |> filter(fn: (r) => r._measurement == \"network\" and r.label == \"${label}\" and r._field == \"length\")\r\n\r\nstartP = all\r\n      |> first()\r\n      |> map(fn: (r) => ({r with _value: 0}))\r\n      |> map(fn: (r) => ({r with timeA: r._time}))\r\n\r\nstopP = all\r\n      |> last()\r\n      |> map(fn: (r) => ({r with _value: 0}))\r\n      |> map(fn: (r) => ({r with timeA: r._time}))\r\n\r\njoin.inner(left: startP, right: stopP, on: (l, r) => l._value == r._value, as: (l, r) => ({l with timeB: r._time}))  \r\n      |> keep(columns: [\"timeA\", \"timeB\"])\r\n      |> map(fn: (r) => ({r with timeA: int(v: uint(v: r.timeA)) / 1000000000}))\r\n      |> map(fn: (r) => ({r with timeB: int(v: uint(v: r.timeB)) / 1000000000}))"
    }
   ]
  },
  { "title": "Basic info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "IPs GeoHeatMap",
   "type": "geomap",
   "description": "A Heat map which shows the GeoIP of the connected IPs and the relative weight which is based on how many times an IP has been seen in the traffic capture.",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and r.label == \"${label}\"\r\n    and (r._field == \"lat\" or r._field == \"lon\" or r._field == \"country\"))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "IPs Geo distribution",
   "type": "piechart",
   "description": "Pie chart shows the numbers and proportion of Geo IPs. This is the outgoing traffic. The total of \"Value\" may be different from the Incoming vs Outgoing Pie chart below because sometimes it happens that the database ha no data about an IP and that IP is not counted in this pie chart.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and r._field == \"country\" and r.label == \"${label}\")\r\n  |> group(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"country\"})\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> rename(columns: {_value: \"\"})\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Power consumption (mean) / $period",
   "type": "timeseries",
   "description": "Shows the power consumption over time. If there are empty spots, it means no data was captured in that moment.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"power\" and r.label == \"${label}\" and r._field == \"load\")\r\n  |> aggregateWindow(every: ${period}, fn: mean)\r\n  |> rename(columns: {_value: \"load\"})"
    }
   ]
  },
  {
   "title": "Number of packets / $period",
   "type": "timeseries",
   "description": "Shows the number of packets sent and received.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and r.label == \"${label}\" and r._field == \"No\")\r\n  |> aggregateWindow(every: ${period}, fn: count)\r\n  |> rename(columns: {_value: \"packets\"})"
    }
   ]
  },
  {
   "title": "Packets length for ${l4}:${port}",
   "type": "histogram",
   "description": "Shows the length of the packets filtered by \"Layer 4\" and \"Port\" variables.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Packets length for ${l4}:${port}",
   "type": "timeseries",
   "description": "Shows the length of the packets filtered by \"Layer 4\" and \"Port\" variables.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and r.label == \"${label}\" and (r._field == \"transport\" or r._field == \"length\"\r\n    or r._field == \"dport\"))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.transport == \"${l4}\" and r.dport == ${port})\r\n  |> drop(columns: [\"dport\", \"transport\"])"
    }
   ]
  },
  {
   "title": "Destination IPs for ${l4}:${port}",
   "type": "piechart",
   "description": "A Pie Chart that shows which are the most IPs present in the traffic capture for the filtered Layer 4 and Port value.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"dst\" or r._field == \"transport\" or r._field == \"dport\")\r\n    and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.transport == \"${l4}\" and r.dport == ${port})\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"dst\"])\r\n  |> count()\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Table of hostnames for ${l4}:${port}",
   "type": "table",
   "description": "Shows the hostnames with their relative IP and if they have been flagged for the filtered Layer 4 and Port. Count indicates how many times an IP have been seen in the outgoing traffic.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"flagged\" or r._field == \"private\" \r\n    or r._field == \"hostname\" or r._field == \"dst\" or r._field == \"transport\" or r._field == \"dport\") and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.transport == \"${l4}\" and r.dport == ${port})\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"flagged\", \"hostname\", \"dst\"])\r\n  |> count()\r\n  |> group()\r\n  |> rename(columns: {_value: \"count\"})\r\n"
    }
   ]
  },
  {
   "title": "Scatter plot ",
   "type": "xychart",
   "description": "A scatter plots which compare the power and the number of packets sent/received.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "nt = from(bucket: \"BT_EX\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => (r._measurement == \"network\" and r.label == \"${label}\" and r._field == \"length\"))\r\n        |> aggregateWindow(every: ${period}, fn: count)\r\n        |> map(fn: (r) => ({_value: float(v: r._value), _time: r._time, _field: \"packets\"}))\r\n\r\npt = from(bucket: \"BT_EX\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => (r._measurement == \"power\" and r.label == \"${label}\" and r._field == \"load\"))\r\n        |> aggregateWindow(every: ${period}, fn: mean)\r\n        |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"power\"}))\r\n\r\nunion(tables: [nt, pt])\r\n        |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")        "
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Number of bytes (sum) / $period",
   "type": "barchart",
   "description": "Shows the number of total bytes sent/received.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and r.label == \"${label}\" and r._field == \"length\")\r\n  |> aggregateWindow(every: ${period}, fn: sum)\r\n  |> rename(columns: {_value: \"bytes\"})"
    }
   ]
  },
  {
   "title": "Number of packets / $period",
   "type": "barchart",
   "description": "A bar chart which can be useful to see in which time frame most packets has been sendt and received.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Destination IPs (private IPs exluded)",
   "type": "piechart",
   "description": "A Pie Chart that shows which are the most IPs present in the traffic capture. It only considers the outgoing traffic. Otherwise private IPs would flood the chart.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"dst\" or r._field == \"private\") and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.private == false)\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"dst\"])\r\n  |> count()\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Destination IPs (private IPs exluded)",
   "type": "marcusolsson-treemap-panel",
   "description": "Similar to the Pie Chart, this Treemap shows the most present IPs in the outgoing traffic. When hovering over a data, it will also shows its hostname and if it has been flagged as adware or malware.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"dst\" or r._field == \"hostname\"\r\n    or r._field == \"flagged\" or r._field == \"private\") and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.private == false)\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"dst\", \"hostname\", \"flagged\"])\r\n  |> count()\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Incoming vs Outgoing traffic",
   "type": "piechart",
   "description": "Shows the number of incoming and outgoing traffic.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and r._field == \"private\" and r.label == \"${label}\")\r\n  |> group(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"private\"})\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> rename(columns: {_value: \"\"})\r\n  |> map(fn: (r) => ({r with type: if r.private == true then \"incoming\" else \"outgoing\"}))\r\n  |> drop(columns: [\"private\"])\r\n  |> group(columns: [\"type\"])\r\n  "
    }
   ]
  },
  {
   "title": "Number of hostnames flagged as adware or malware",
   "type": "piechart",
   "description": "Shows how many hostnames have been flagged as adware or malware. False mean not flagged. It shows also how many distinct hostnames have been contacted.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 77 },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"flagged\" or r._field == \"private\" \r\n    or r._field == \"hostname\") and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.private == false)\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"flagged\"])\r\n  |> distinct(column: \"hostname\")\r\n  |> count()\r\n  |> rename(columns: {_value: \"\"})\r\n"
    }
   ]
  },
  {
   "title": "Table of hostnames",
   "type": "table",
   "description": "Shows the hostnames with their relative IP and if they have been flagged. Count indicates how many times an IP have been seen in the outgoing traffic.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"flagged\" or r._field == \"private\" \r\n    or r._field == \"hostname\" or r._field == \"dst\") and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.private == false)\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"flagged\", \"hostname\", \"dst\"])\r\n  |> count()\r\n  |> group()\r\n  |> rename(columns: {_value: \"count\"})\r\n"
    }
   ]
  },
  {
   "title": "TCP flags",
   "type": "piechart",
   "description": "Shows the TPC flags in the packets. Can be useful to know how many TCP connections have been established, but also TCP retransmit and other useful data.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and r._field == \"flags\" and r.label == \"${label}\")\r\n  |> group(columns: [\"_value\"])\r\n  |> rename(columns: {_value: \"flags\"})\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> rename(columns: {_value: \"\"})\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Transport protocol  (private IPs exluded)",
   "type": "piechart",
   "description": "Shows the number and proportion of the protocols used at layer 4 (transport). Combines with the port Pie chart it can be useful to know if QUICK was used or other protocols.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"transport\" or r._field == \"private\") and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.private == false)\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"transport\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"\"})\r\n  "
    }
   ]
  },
  {
   "title": "Destination Ports (private IPs exluded)",
   "type": "piechart",
   "description": "Shows how many times the ports have been used. \"No port\" means no port was used for that packet, only a few protocols use no port.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\" and (r._field == \"dport\" or r._field == \"private\") and r.label == \"${label}\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.private == false)\r\n  |> set(key: \"_value\", value: \"1\")\r\n  |> toInt()\r\n  |> group(columns: [\"dport\"])\r\n  |> count()\r\n  |> rename(columns: {_value: \"\"})\r\n"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Power consumption (sum) / $period",
   "type": "barchart",
   "description": "Shows the total power consumption.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"BT_EX\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"power\" and r.label == \"${label}\" and r._field == \"load\")\r\n  |> aggregateWindow(every: ${period}, fn: sum)\r\n  |> rename(columns: {_value: \"load\"})"
    }
   ]
  },
  {
   "title": "Histogram power consumption (mean) / $period",
   "type": "histogram",
   "description": "Shows how many time a range of values have been captured",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "panelId": 9 }
   ]
  }
 ]
}